apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 192.168.56.10
      user: root
      port: 22
      keyPath: <path-to-ssh-key>
    role: controller
    privateInterface: eth1
  - ssh:
      address: 192.168.56.11
      user: root
      port: 22
      keyPath: <path-to-ssh-key>
    role: worker
    privateInterface: eth1
  - ssh:
      address: 192.168.56.12
      user: root
      port: 22
      keyPath: <path-to-ssh-key>
    role: worker
    privateInterface: eth1
  k0s:
    version: 1.25.2+k0s.0
    dynamicConfig: false
